travis:
  secure:
    BINSTAR_TOKEN: CEU/9gBME6Ct/JdOBtFv/JxMQvXd2eqqHwB465FvJO5DTGWG1Jwm+MbZeym+wCgEzgnNFint3JJoh1kpcWYkzwcbIwm1t7xWgPM2HvLuCaLU7P15yuFKSeibMTJEjummIOjFjoucldWZ15zNWr3xQTOYdXyAlTfqGYzr8RY84UkG+Rb0j/kbbqsvhjpN4pqWIWZH5gttaG8abPVZBGHps3N0ZNM4k1yV1GtwQQi/0tKLPCapygj8GjysNgyossGtg7LWZ6Xgwf0B2bFWICP7mA8DROR4ehklDc/VdNggE20XFD0wVZggxq/Pq7CExO3NmkUMPgq+mO6/bLoK/goE61CMXs6yMFMDGB48JIOoRCpbVxJ+6AjXioSZznIh/PxOZfOmraL5qM0D3WQ6MTBZaBcnJfOQsg9Cs7W1ClwSpdYkJJ4fX/YPD8j8sLVg44xLOkCV5UE1cdDQCdhlrMgcqkarD4lW/hQKNz2RbpHYVQ7j7PdrEvZGJDiq25r6jNk07Bfmy/h3iQOhmxM9dtyEEHjIBG3fgA7VRrHBFgADCoe9rYLKDIyPe3JahkiL7rp0FaXzvD6jk4HOkgNPl61PsiPEZx90H0eCziLIbr6Db/nWbyXD3F147DYpUP+pcVmjLPwcS7/8sihii/61eYjgT+7U1SZcawzod6k3U8u0r7A=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
